- name: Update
  apt:
    update_cache: yes

- name: Upgrade
  apt:
    upgrade: safe

    
- name: Add Hosts records 
  lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        insertafter: EOF
  with_items:
      - "192.168.44.15 mailserver-1.test.loc mailserver-1"
      - "192.168.44.16 mailserver-2.test.loc mailserver-2"
  when: ansible_os_family == "Debian"